<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="CounterStrikeSharp.API" Version="*" >
			<HintPath>D:/dev/CS2PluginsDev/addons/counterstrikesharp/api/CounterStrikeSharp.API.dll</HintPath>
	    </PackageReference>
    </ItemGroup>
	
	<ItemGroup>
		<EmbeddedResource Include="lang\*.json" />
	</ItemGroup>

</Project>
